

CREATE TABLE UserInfo(
	UserId INT IDENTITY(1,1) PRIMARY KEY,
	Nama VARCHAR(255) NOT NULL,
	NoHp VARCHAR(20) NOT NULL,
	)

CREATE TABLE Paket (
    PaketId INT PRIMARY KEY IDENTITY(1,1),
    NamaPaket VARCHAR(255) NOT NULL,
	Durasi VARCHAR(50) NOT NULL,
    Harga DECIMAL(10, 2) NOT NULL
)

CREATE TABLE Akun (
    AkunId INT PRIMARY KEY IDENTITY(1,1),
    Email VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'Tersedia'
);

CREATE TABLE InfoAkun (
    InfoAkunId INT PRIMARY KEY IDENTITY(1,1),
    AkunId INT,
	MasaAktifAkun DATE,
    JumlahUser INT DEFAULT 0, 
    MaksUser INT DEFAULT 5,
	FOREIGN KEY(AkunId) REFERENCES Akun(AkunId)
	ON DELETE CASCADE ON UPDATE CASCADE
)


CREATE TABLE Transaksi (
    TransaksiId INT PRIMARY KEY IDENTITY(1,1),
    UserId INT,
    AkunId INT,
	PaketId INT,
	MasaSewa VARCHAR(20) DEFAULT 'Aktif',
    TanggalMulai DATETIME DEFAULT GETDATE(),
	TanggalAkhir DATETIME,
	FOREIGN KEY (UserId) REFERENCES UserInfo(UserId)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (AkunId) REFERENCES Akun(AkunId)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (PaketId) REFERENCES Paket(PaketId)
		ON DELETE CASCADE ON UPDATE CASCADE
);